const imageArray = [

    {id: 1,
     name: "watermelon",
     image: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F30%2Fstack-of-picked-watermelons-92e16796.jpg&q=60",
     desc: "A large oblong or roundish fruit with a hard green or white rind often striped or variegated, a sweet watery pink, yellowish, or red pulp, and usually many seeds.",
     carb: "Carbs: 8g",
     prot: "Protien: 0.6g",
     sug: "Sugars: 6g",
     cal: "Calories: 30"},


    {id: 2,
     name: "cherry",
     image: "https://cdn.britannica.com/60/174560-050-5A33606F/cherries-Cluster.jpg",
     desc: "The acid content of the sweet cherry is low. The higher acid content of the sour cherry produces its characteristic tart flavour.",
     carb: "Carbs: 12g",
     prot: "Protien: 1g",
     sug: "Sugars: 8g",
     cal: "Calories: 50"},

    {id: 3,
     name: "strawberry",
     image: "https://www.macmillandictionary.com/external/slideshow/full/160279_full.jpg",
     desc: "Strawberries are soft, sweet, bright red berries. They're also delicious. Strawberries have tiny edible seeds, which grow all over their surface.",
     carb: "Carbs: 5.5g",
     prot: "Protien: .8g",
     sug: "Sugars: 5.9g",
     cal: "Calories: 29"},

    {id: 4,
     name: "blueberry",
     image: "https://cdn.shopify.com/s/files/1/0059/8835/2052/products/Brightwell_Blueberry_1_650x.jpg?v=1619044035",
     desc: "Their color can range from blue to purple. They are often eaten fresh but can also be enjoyed frozen, added to a wide variety of baked goods, or juiced or pureed.",
     carb: "Carbs: 5.5g",
     prot: "Protien: 0g",
     sug: "Sugars: 5.4g",
     cal: "Calories: 29"},

    {id: 5,
     name: "banana",
     image: "https://cdn-prod.medicalnewstoday.com/content/images/articles/271/271157/bananas-chopped-up-in-a-bowl.jpg",
     desc: "A banana is a curved, yellow fruit with a thick skin and soft sweet flesh.",
     carb: "Carbs: 22g",
     prot: "Protien: 1g",
     sug: "Sugars: 17g",
     cal: "Calories: 96"},

    {id: 6,
     name: "pear",
     image: "https://techcrunch.com/wp-content/uploads/2019/09/GettyImages-74353539.jpeg",
     desc: "A pome fruit of a tree (genus Pyrus, especially P. communis) of the rose family that typically has a pale green or brownish skin, a firm juicy flesh, and an oblong shape.",
     carb: "Carbs: 15g",
     prot: "Protien: 0.4g",
     sug: "Sugars: 10g",
     cal: "Calories: 57"},
     
    {id: 7,
     name: "tomato",
     image: "https://www.almanac.com/sites/default/files/users/The%20Editors/tomato-blue-beauty-wild-boar-dsc08449.jpg",
     desc: "They are usually red, scarlet, or yellow, though green and purple varieties do exist, and they vary in shape from almost spherical to oval and elongate to pear-shaped.",
     carb: "Carbs: 3.9g",
     prot: "Protien: 0.9",
     sug: "Sugars: 2.6g",
     cal: "Calories: 74"}
]